### ISSUE TITLE
求教

### ISSUE THREAD

**Issue by Ruiii1** [zc402/ctpgr-pytorch#1]
运行在windows下，没有gpu可以吗

**Comment by zc402** [comment]
你好，我没测试过，按说pytorch会同时支持CPU和GPU，不过即使能运行肯定也是很慢很慢，难以使用。

**Comment by Ruiii1** [comment]
这个项目可以运行于linux下吗？？？

**Comment by zc402** [comment]
当然可以啦。pytorch项目一般都是运行于linux下的，在Windows运行效率比较低。

**Comment by zc402** [comment]
不过由于众所周知的原因，我们需要科学上网，而linux下面相关的工具比较难用，windows会好得多。因此我一般是windows开发、linux训练。如果没有特殊需求，就用windows吧，架设环境快，不需要瞎折腾，训练会慢一点也无所谓。

**Comment by Ruiii1** [comment]
十分感谢您的帮助

**Comment by Ruiii1** [comment]
想请问一下您的显卡是什么型号啊

**Comment by zc402** [comment]
GTX1080TI、GTX980M、GTX970。我这个属于小网络了，有个3G显存就可以训练

**Comment by Ruiii1** [comment]
> GTX1080TI、GTX980M、GTX970。我这个属于小网络了，有个3G显存就可以训练

谢谢😁😁
