### ISSUE TITLE
求问一些问题

### ISSUE THREAD

**Issue by qq969808324** [zc402/ctpgr-pytorch#2]
怎么去训练模型呢，因为模型下载下来已经是训练好的了

**Comment by zc402** [comment]
ctpgr.py 里面有所有可用参数的列表，其中包括训练关键点网络和手势识别网络所需的参数。

**Comment by qq969808324** [comment]
好的，那个训练点网络的数据集能发我一份吗，邮箱是969808324@qq.com。谢谢啦

**Comment by qq969808324** [comment]
或者分享一下网盘地址也行

**Comment by zc402** [comment]
网盘发你邮箱了。我毕竟不是数据集拥有者，不能公开分享在这里。

**Comment by qq969808324** [comment]
谢谢了

**Comment by zc402** [comment]
不客气

**Comment by alexlandive** [comment]
您好吧、，训练点网络的数据集可以分享给我一份吗？我的qq是729063509@qq.com非常感谢

**Comment by qq969808324** [comment]
百度网盘 链接: https://pan.baidu.com/s/1dUgATvwMxz6DVlRL-wHgRA 提取码: w8mq



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月9日(周日) 下午2:13
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zc402/ctpgr-pytorch] 求问一些问题 (#2)




 
***@***.***非常感谢

**Comment by alexlandive** [comment]
@qq969808324 非常感谢，您是在做这个项目的相关的工作吗？不知道可不可以交流一下呢？
